### ISSUE TITLE
brew install python3 instead of recommending people install Xcode

### ISSUE THREAD

**Issue by xiurobert** [Drovosek01/adobe-packager#28]
Works just as well.

**Comment by VaslD** [comment]
Why though? You already need Xcode Command Line Tools (what `xcode-select --install` does) to use Homebrew.

That command does not install Xcode app, it installs about 1 GB of scripting environment and macOS SDK that are also **part of** the 13 GB Xcode app.

**Comment by xiurobert** [comment]
Not TOO sure about the specifics but does Xcode cli contain python3?

**Comment by VaslD** [comment]
Not the latest minor/patch version (because its release schedule is tied to Xcode not Python) but yes. Both Xcode and CLT installs Python 3 and related components (like `pip3`).

macOS also comes with a built-in `python3` command that installs CLT the first time it’s invoked. So there really is no need to brew anything if someone just came here to grab Photoshop. Homebrew has a somewhat steep learning curve to non-developers.

**Comment by xiurobert** [comment]
Gotcha. I'll close the issue if that is the case.
