### ISSUE TITLE
Just a Thank you

### ISSUE THREAD

**Issue by inspiredearth** [Drovosek01/adobe-packager#3]
Hi @Drovosek01 

No issue. Just a message to thank you for taking the initiative to gather up this script into a new project, and for adding an excellent `readme.md`. I've been tracking this script across its various iterations since it emerged via ayyybe, and it's great to see the current working version now has a good home.

Be well ...

**Comment by thpryrchn** [comment]
No Problem. It also has helped me with improving the code :)

**Comment by zombibunny** [comment]
Hi @Drovosek01 

Great work!! 

Though at line 37 in ccdl.command I had to add --user for it to install tqdm. Otherwise, I was getting permission error.

37 python -c "import tqdm" || pip3 install --user tqdm

**Comment by thpryrchn** [comment]
> Hi @Drovosek01 
> 
> 
> 
> Great work!! 
> 
> 
> 
> Though at line 37 in ccdl.command I had to add --user for it to install tqdm. Otherwise, I was getting permission error.
> 
> 
> 
> 37 python -c "import tqdm" || pip3 install --user tqdm

Hmm. Maybe I need to add a `sudo` in front of it to install system wide.

**Comment by thpryrchn** [comment]
> Hi @Drovosek01
> 
> Great work!!
> 
> Though at line 37 in ccdl.command I had to add --user for it to install tqdm. Otherwise, I was getting permission error.
> 
> 37 python -c "import tqdm" || pip3 install --user tqdm

Fixed it in the latest Commits :)

**Comment by zombibunny** [comment]
Great news.Once again thank you for the update on the Adobe Packager manager.

**Comment by Drovosek01** [comment]
I am glad that this repository benefits not only me, but the work of the code from this repository is not my merit. I just combined it all in chronological order, corrected the formatting and corrected 1 line so that python does not download the file, but takes the file from the current directory.

We should thank the people whose links to the pages are listed in the "[Used code](https://github.com/Drovosek01/adobe-packager#used-code)" section in the readme file.

If you want to say thank you, just put an star to this repository, and if you have a problem with the code from the repository, create a new issue.
