### ISSUE TITLE
Requirement already satisfied: tqdm... You need tqdm!

### ISSUE THREAD

**Issue by 2yxhrc** [Drovosek01/adobe-packager#9]
when running the command file it returns this

```
requests found!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tqdm'
Requirement already satisfied: tqdm in ./Library/Python/3.9/lib/python/site-packages (4.62.3)
starting ccdl
Trying to Install required module: tqdm

Requirement already satisfied: tqdm in /Users/x/Library/Python/3.9/lib/python/site-packages (4.62.3)
You need tqdm!
                install it from http://pypi.python.org/pypi/tqdm
                or run: pip3 install tqdm.

[Process completed]
```

tqdm should already be installed and it tells me this when I pip3 install tqdm.
sorry I am not very advanced but having trouble here!

**Comment by leifadev** [comment]
Do you have [homebrew](brew.sh) installed?
According to their website it is for making progress bars, in the script. First try using `pip` instead of `pip3`, the script may use that instead of pip3.

If I recall the script installs homebrew if hasn't then it will move on without any other attempt to install python. The thing is python is already on macOS (just a minor version of it, like all OS), and maybe if you dont have homebrew installed, that me be a reason why for my solution

**Comment by 2yxhrc** [comment]
I reinstalled home-brew as part of my trouble shooting. sorry im really not that technical, I understood by what u wrote to try  (not sure if this is what you meant I should do)
`pip install tqdm`
returning
`Requirement already satisfied: tqdm in ./Library/Python/3.9/lib/python/site-packages (4.62.3)`

I found some posts on reddit of people with the same issue and they said line 37 needed --user for elevated permissions however it looks like the current version already has the amended --user in line 37

(again sorry for my lack of understanding)

**Comment by leifadev** [comment]
It looks like it is already installed then. Try reinstalling the package running with superuser privileges￼
